Understand and use 2D NumPy arrays (matrices), including how to check their shape, and how to index and slice them to access specific rows, columns, and elements.

2D Arrays (Matrices): If a 1D array is a single row of numbers, a 2D array is a grid of numbers, like a spreadsheet or a tic-tac-toe board. It has rows and columns.

# This is a 2x3 matrix (2 rows, 3 columns)
matrix = np.array([
    [1, 2, 3],  # Row 0
    [4, 5, 6]   # Row 1
])

# Indexing (2D): Accessing a single element is like giving its coordinates. The syntax is array[row, col]. Remember, indexing starts at 0.

matrix[0, 0] would give you 1.

matrix[1, 2] would give you 6.

# Slicing (2D): This is how you grab sections of your data. It uses the colon : (which means "get everything").

Get a whole row: matrix[0, :] (Get row 0, all columns) -> [1, 2, 3]

Get a whole column: matrix[:, 0] (Get all rows, column 0) -> [1, 4]

Get a sub-grid: matrix[:1, 1:3] (Get row 0, and columns 1 & 2) -> [[2, 3]]

In [2]:
import numpy as np

In [5]:
#1. From a List of lists

list_of_lists = [
    [5,10,15],
    [20,25,30],
    [35,40,45]
]
matrix = np.array(list_of_lists)
print("My matrix : ")
print(matrix)

My matrix : 
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [7]:
#2. Check its shape

print(f"Matrix shape : {matrix.shape}")  #answer == (3,3)

Matrix shape : (3, 3)


In [10]:
#3. Create a 2 x 4 matrix of all zeros

zeros_matrix = np.zeros((2,4))
print("\n Xeros Matrix:")
print(zeros_matrix)


 Xeros Matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
#4. try ones matrix for 5 x 5

one_mat = np.ones((5,5))
print("so the 5x5 matrix of 1 would look like\n")
print(one_mat)

so the 5x5 matrix of 1 would look like

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Indexing Practice

In [14]:
# Get the number 10 (row 0, col 1) [from the initial array we built named list of lists]

el_10 = matrix [0,1]
print(f"Element at [0,1] is : {el_10}")

Element at [0,1] is : 10


In [15]:
#2. get the number 45 , we do know it 3x3 but in comp indexing begins from 0 so .. 2,2

el_45 = matrix[2,2]
print(f"element at [2,2] is : {el_45}")

element at [2,2] is : 45


In [16]:
# Get the number 35 (row 2, col 0)
el_35 = matrix[2, 0]
print(f"Element at [2, 0] is: {el_35}")

Element at [2, 0] is: 35


# Slicing Practice (Get sections)

In [17]:
#1. get the entire first row

row_0 = matrix[0,:]
print(f"Row 0 : {row_0}")

Row 0 : [ 5 10 15]


In [18]:
#2. Get the entire second column

col_1 = matrix[:,1]
print(f"Column 1 : {col_1}")

Column 1 : [10 25 40]


In [19]:
# 3. Get a sub-matrix (top right 2x2 corner)
# Rows 0 and 1 (written as :2)
# Columns 1 and 2 (written as 1:)

top_right = matrix[:2,1:]
print("\nTop right of 2 x 2")
print(top_right)


Top right of 2 x 2
[[10 15]
 [25 30]]
